### ISSUE TITLE
Android: Provide a single entrypoint view that allows customers to get new tools without adding each tool individually

### ISSUE THREAD

**Issue by okdistribute** [getditto/DittoAndroidTools#24]
* Menu list of the tools by name.
* Click the tool and see the full-view
* Easily switch between tools with a visible menu

**Comment by rajramsaroop** [comment]
Thinking about expanding on the details of this story a little bit more:

- Create a UI that a client can place in their app in whatever screen they think is appropriate (like a developer settings screen).
- The UI will be a menu that will allow a user to navigate to each of the tools.
- On the Android side I'm hoping this can just be a single dependency so that the user doesn't have to pull in separate dependencies for each of the tools.
- For testing this out or being able to see what it will look like, I will be adding it as a separate module and then including that module in the demo app that's part of the tools repo.
- (Nice to have) In the future, as a separate story we will look at publishing to Maven locally (I was having issues) so that in can be tested in demo apps locally first. I think this presents a slightly more realistic implementation.
- Existing modules can still be imported if some clients prefer to customize things more.

Let me know if I'm missing anything.

**Comment by okdistribute** [comment]
Sounds great. Whatever will get this into customers hands faster
